name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm ci

      - name: Lint JavaScript
        run: npm run lint:js

      - name: Lint prettier
        run: npm run lint

      - name: Lint Style
        run: npm run lint:style

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build

      - name: Trigger CD
        uses: octo-linker/action-workflow-dispatch@v2.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          workflow: CD
          ref: main
          inputs: |
            environment: production
